# -*- coding: utf-8 -*-
"""implementation of frequency analysis.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ruZQnE9VWPM94CJwDEO2zCC4lfkC5iE1
"""

cipher = "khcjtdfiinnmhuipuggfhhuygfghkkmjhuyytfggghkkkkllpiuytrdssfghnmlpiuytfrfddddfrgghhjjuujugggffrtttyyhuujjiiik"
alphabet = "abcdefghijklmnopqrstwxyz"

freq = {}
for c in alphabet:
   freq[c] = 0
   letter_count = 0
   for c in cipher:
     if c in freq:
      freq[c] +=1 #77777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777788888888888888888888888888888888
     letter_count +=1

     for c in freq:
      freq[c] = round(freq[c]/letter_count, 4)

      new_line_count = 0
      for c in freq:
        print(c,':',freq[c], end='')
        if new_line_count % 3 == 2:
          print()
          new_line_count+=1